apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-manifest-api
spec:
  template:
    spec:
      containers:
      - name: model-manifest-api
        image: taffarelo3/model-manifest-api:82073dd0e5ab6543b6050be2c9ee4498d8fa513a