apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-manifest-api
spec:
  template:
    spec:
      containers:
      - name: model-manifest-api
        image: dockerhub/model-manifest-api:latest